name: Environment

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Print the current working directory
        run: pwd
      - name: Print files and folders in the current directory
        run: ls -la
      - name: Print Git branches
        run: git branch
      - name: Print executable paths
        run: echo $PATH
      - name: Print the Node.js version
        run: node -v
      - name: Print Node.js paths 
        run: which -a node
